from pydantic import BaseModel, Field
from typing import List

class ActionItem(BaseModel):
    task: str
    urgency: str = Field(..., description="High, Medium, or Low")

class MorningBriefing(BaseModel):
    """
    The final, structured output generated by the AI agent for the CXO.
    """
    shape_of_the_day: str = Field(..., description="A 2-3 sentence summary of the day's cadence")
    critical_attention_items: List[str] = Field(..., description="Emails or events requiring immediate action")
    open_commitments: List[ActionItem]
    pre_meeting_flags: List[str] = Field(..., description="Context for high-stakes meetings happening today")